apiVersion: conventions.carto.run/v1alpha1
kind: PodIntent
metadata:
  name: volume-mount-test
spec:
  serviceAccountName: default
  template:
    metadata:
      annotations:
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: test
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: test
        jp.vmware.tanzu/volumemount: nfs
        jp.vmware.tanzu/volumemount-server: 1.1.1.1
        jp.vmware.tanzu/volumemount-path: path.path
        jp.vmware.tanzu/volumemount-mountpath: path.mountpath
    spec:
      containers:
        - image: harbor.cl01.lespaulstudioplus.info/docker-hub/library/nginx
          name: workload
          resources: {}
          securityContext:
            runAsUser: 1000
      serviceAccountName: default
