apiVersion: conventions.carto.run/v1alpha1
kind: PodIntent
metadata:
  name: py-func-test
spec:
  serviceAccountName: default
  template:
    metadata:
      annotations:
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: py-func
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: py-func
    spec:
      containers:
        - image: harbor.lespaulstudioplus.info/tap/supply-chain/py-func-python-demo@sha256:f21f511193119f06f1e537cff61a67f52df2ee0df021a20378391a0e88fe2f55
          name: workload
          resources: {}
          securityContext:
            runAsUser: 1000
      serviceAccountName: default
